'use strict';

export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST';
export const RECEIVE_ORDER_LIST = 'RECEIVE_ORDER_LIST';
export const FETCH_SHOPCAR_LIST = 'FETCH_SHOPCAR_LIST';
export const RECEIVE_SHOPCAR_LIST = 'RECEIVE_SHOPCAR_LIST';